os: linux
language: python
dist: focal
stage: Run Premium vm build
group: edge
name: Premium VM builds
python: '3.9'
arch: amd64
vm:
  size: 2x-large
script:
- |-
  df -h
  lspci
  echo "Going for sleep"
  for ((i=1; i<=1; i++)); do
    echo "Elapsed minutes: $i"
    sleep 60s
  done

