os: linux
dist: focal
jobs:
  include:
    - stage: "GPU medium build"
      name: "GPU medium job"
      dist: focal
      addons:
        tensorflow: 2.6.2
        blender: 3.4.1
      vm:
        size: 'gpu-medium'
      language: python
      python:
        - "3.9"
      arch: 'amd64'
      script: echo


